GENCCODE_ASSEMBLY_TYPE=-a gcc
SO=so
SOBJ=so
A=a
LIBPREFIX=lib
LIB_EXT_ORDER=.78.3
COMPILE=/home/task_HeepgnZ8RCWnS_0/croot/icu_1782931880337/_build_env/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /data/projet3/conda_temporaire/env_ncbi/include -D_REENTRANT  -DU_HAVE_ELF_H=1  -DU_ALL_IMPLEMENTATION -DU_ATTRIBUTE_DEPRECATED= -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data/projet3/conda_temporaire/env_ncbi/include -fdebug-prefix-map=/home/task_HeepgnZ8RCWnS_0/croot/icu_1782931880337/work=/usr/local/src/conda/icu-78.3 -fdebug-prefix-map=/data/projet3/conda_temporaire/env_ncbi=/usr/local/src/conda-prefix -std=c11 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -c
LIBFLAGS=-I/data/projet3/conda_temporaire/env_ncbi/include -DPIC -fPIC
GENLIB=/home/task_HeepgnZ8RCWnS_0/croot/icu_1782931880337/_build_env/bin/x86_64-conda-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data/projet3/conda_temporaire/env_ncbi/include -fdebug-prefix-map=/home/task_HeepgnZ8RCWnS_0/croot/icu_1782931880337/work=/usr/local/src/conda/icu-78.3 -fdebug-prefix-map=/data/projet3/conda_temporaire/env_ncbi=/usr/local/src/conda-prefix -std=c11 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/data/projet3/conda_temporaire/env_ncbi/lib -Wl,-rpath-link,/data/projet3/conda_temporaire/env_ncbi/lib -L/data/projet3/conda_temporaire/env_ncbi/lib  -shared -Wl,-Bsymbolic
LDICUDTFLAGS=-nodefaultlibs -nostdlib
LD_SONAME=-Wl,-soname -Wl,
RPATH_FLAGS=
BIR_LDFLAGS=-Wl,-Bsymbolic
AR=/home/task_HeepgnZ8RCWnS_0/croot/icu_1782931880337/_build_env/bin/x86_64-conda-linux-gnu-ar
ARFLAGS=r
RANLIB=/home/task_HeepgnZ8RCWnS_0/croot/icu_1782931880337/_build_env/bin/x86_64-conda-linux-gnu-ranlib
INSTALL_CMD=/usr/bin/install -c
